# Generated by Django 5.1.1 on 2024-10-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_signup_data',
            new_name='User_data',
        ),
    ]
